services:
  pg:
    image: postgres:16
    container_name: this_database
    environment:
      - POSTGRES_USER=ahmed
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=green_taxi
    volumes:
      - "D:/zoomCamp/HW_W1/green_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5433:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - "5050:80"
  
  my-python-services: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_container
    volumes:
      - "D:/zoomCamp/HW_W1/python_code:/app"
    working_dir: /app
    depends_on:
      - pg
    command: python /app/ingest_data.py